export enum TechnologyType {
  COMMUNICATION_FRAMEWORKS = "COMMUNICATION_FRAMEWORKS",
  DATABASES = "DATABASES",
  FRAMEWORKS_CONCEPTS = "FRAMEWORKS_CONCEPTS",
  OTHERS = "OTHERS",
  PROGRAMMING_LANGUAGES = "PROGRAMMING_LANGUAGES",
  PROJECT_MANAGEMENT = "PROJECT_MANAGEMENT",
  TESTING = "TESTING",
  TOOLS = "TOOLS",
}
