export enum TechnologyType {
  PROGRAMMING_LANGUAGES = "PROGRAMMING_LANGUAGES",
  DATABASES = "DATABASES",
  FRAMEWORKS_CONCEPTS = "FRAMEWORKS_CONCEPTS",
  TESTING = "TESTING",
  COMMUNICATION_FRAMEWORKS = "COMMUNICATION_FRAMEWORKS",
  TOOLS = "TOOLS",
  PROJECT_MANAGEMENT = "PROJECT_MANAGEMENT",
}
