export enum Technology {
  ABAP = "ABAP",
  BALSAMIQ = "Balsamiq",
  BLUEPRINT_JS = "Blueprint JS",
  ENTERPRISE_ARCHITECT = "Enterprise Architect",
  FIGMA = "Figma",
  GIT = "Git",
  JAVA = "Java",
  JAVASCRIPT = "JavaScript",
  JEST = "Jest",
  ICF_SERVICE = "ICF-Service",
  OPEN_SQL = "Open SQL",
  REACT = "React",
  REACT_ROUTER_DOM = "react-router-dom",
  REST = "REST",
  SCRUM = "Scrum",
  SAP_GUI = "SAP GUI",
  SPRING_BOOT = "Spring Boot",
  SCSS = "SCSS",
  TYPESCRIPT = "TypeScript",
  VS_CODE = "Visual Studio Code",
}
